name: Format Code

on:
    push:
        branches: [ "main", "format-test" ]
    pull_request:
        branches: [ "main", "format-test" ]
    workflow_run:
        workflows: ["Build and Test"]
        types:
            - completed

jobs:
    format:
        # if: github.event.workflow_run.conclusion == 'success'
        runs-on: macos-14

        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x
            - name: Install CSharpier
              run: dotnet tool install csharpier
            - name: Format with CSharpier
              run: dotnet csharpier .
            - name: Format with dotnet format
              run: |
                dotnet format style
                dotnet format analyzers
            - name: Check changes
              run: |
                git status
                git diff
            - name: Check branch name
              run: echo ${{ github.ref_name }}
#            - name: Build
#              run: git checkout auto/reformat-
#            - name: Create Pull Request
#              run: gh pr
#              env:
#                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}