name: Prepare Release

on:
    push:
        branches:
            - main
            - deploy_test
    workflow_dispatch:

permissions:
    actions: read
    contents: write
    pull-requests: write

jobs:
    prepare-release:
        name: Increment version and add changelog
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.tags, 'v.*') }} # Commit with v.* tag is a release commit created by this job, no need to create a new release from it
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x
            - name: Increment version
              run: |
                cd src/xpd
                dotnet tool install versionize
                dotnet versionize
            - name: Push version & changelog
              run: |
                  CURRENT_VERSION=$(dotnet versionize inspect)
                  BRANCH_NAME="auto/release-$CURRENT_VERSION"
                  echo "SOURCE_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
                  echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git push --follow-tags origin HEAD:$BRANCH_NAME
            - name: Create Pull Request
              if: env.SOURCE_BRANCH != ''
              env:
                  Target_Branch: ${{ github.ref_name }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: >
                  gh pr create
                  --title "Auto Release $CURRENT_VERSION"
                  --body "This automatic PR increases version to $CURRENT_VERSION and prepares changelog. \
                  Upon merging, app will be packed as dotnet tool and released to nuget.org"
                  --base $Target_Branch
                  --head $SOURCE_BRANCH