name: Publish Nuget

on:
    push:
        tags:
            - 'v.*'
    workflow_dispatch:

jobs:
    publish-nuget:
        name: Publish on nuget.org
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x
            - name: Pack as tool
              run: dotnet pack --configuration Release
#            - name: Deploy to NuGet
#              run: dotnet nuget push src/xpd/nukpg/xpd.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json